name: Trigger Bank Demo Tests
on:
  repository_dispatch:
    types: [trigger-bank-demo-tests]

jobs:
  trigger-bank-demo-tests:
    uses: ./.github/workflows/bank-demo-tests.yml
    with:
      distribution-name: ${{ github.event.client_payload.distribution_name }}
    secrets: inherit
