name: Trigger White Label Deployment
on:
  repository_dispatch:
    types: [trigger-smoke-tests]


jobs:
  run-white-label-build:
    uses: ./.github/workflows/smoke-tests.yml
    with:
      distribution-name: ${{ github.event.client_payload.distribution_name }}
    secrets: inherit
